"""add two new fields for the databases

Revision ID: 688fe92bc473
Revises: 80eac1baf3bb
Create Date: 2019-12-28 19:21:33.993790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688fe92bc473'
down_revision = '80eac1baf3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
